language: ruby
rvm: 2.4.1
before_script: gem install awesome_bot
script: awesome_bot README.md --white-list https://github.com/sindresorhus/awesome,http://issuestats.com/github/ramnes/awesome-mongodb
